added inherited virtual game wrapper
ubclaunchpad/virtual-pet pull request #18
Opened 2022-11-25 09:28 UTC by lou-weng

# Description

- added an inheritedWidget to the root of the project. This widget provides a `VirtualPetGame` instance that child nodes within the app can manipulate
- added a testing page that demonstrates the ability of a page to interact with the `VirtualPetGame`. There is a start and pause button that will play and pause the game's execution.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

N/A this was a app design change, no logic required

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-25 23:26 UTC, wu-jacob approved these changes

2022-11-26 06:00 UTC, mebesius requested changes

2022-11-26 06:00 UTC, mebesius commented on front-end/virtual_pet/lib/inherited_widgets/inherited_virtual_pet_game_wrapper.dart
> +    super.key}) : super(child: child);
Please bring the `})` down to a new line

2022-11-26 06:00 UTC, mebesius commented on front-end/virtual_pet/lib/inherited_widgets/inherited_virtual_pet_game_wrapper.dart
> +  bool updateShouldNotify(InheritedWidget oldWidget) => true;
Do we want this to always return true?

2022-11-27 02:28 UTC, lou-weng commented on front-end/virtual_pet/lib/inherited_widgets/inherited_virtual_pet_game_wrapper.dart
> +  bool updateShouldNotify(InheritedWidget oldWidget) => true;
fixed

2022-11-27 22:40 UTC, lou-weng commented
@mebesius made changes and also rebased eric's changes in

2022-11-27 23:29 UTC, mebesius approved these changes
Thanks for making those changes @lou-weng!

2022-11-28 03:19 UTC, merged